name: learning
description: A new Flutter application.

version: 0.1.0+23

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayer:
    git: git://github.com/pablo-co/audioplayer.git
  chewie: 0.9.6
  cloud_firestore: 0.9.7
  cloud_functions: 0.1.2+1
  cupertino_icons: 0.1.2
  firebase_auth: 0.8.3
  fluro: 1.4.0
  flutter_crashlytics: 0.3.0
  flutter_downloader: 1.1.7
  flutter_facebook_login:
    git:
      url: https://github.com/qurami/flutter_facebook_login.git
      ref: fix-loginkit-dependency
  webview_flutter: 0.3.5+2
  flutter_inapp_purchase: 0.9.2
  flutter_launcher_icons: 0.7.0
  flutter_markdown: 0.2.0
  flutter_redux: 0.5.3
  font_awesome_flutter: 8.0.1
  google_sign_in: 4.0.1+1
  http: any
  path_provider: 0.5.0+1
  redux: 3.0.0
  share: 0.6.0+1
  url_launcher: 5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/clap_people.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/logo.png
    - assets/images/logo_white.png
    - assets/images/mountains.jpg
    - assets/images/splash_bg.jpg
    - assets/images/1x1_transparent.png
    - assets/images/placeholder.jpg
    - assets/images/subscription_bg.jpg
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
          style: italic
          weight: 700

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/icon.png'
